# TTP Assignment 8
### NumPy Arrays

<h4 style="color:blue">Question #1A - Print Array Shape</h4> Using the array <b>A</b> below:<br> A = <br> [[10, 20, 30, 40, 50],<br> &nbsp;[15, 25, 35, 45, 55],<br> &nbsp;[12, 22, 32, 42, 52],<br> &nbsp;[17, 27, 37, 47, 57],<br> &nbsp;[19, 29, 39, 49, 59]]<br><br> Print the <b>shape</b> of the array.<br>

In [1]:
import numpy as np


In [2]:
A = np.array([[10, 20, 30, 40, 50],
 [15, 25, 35, 45, 55],
 [12, 22, 32, 42, 52],
 [17, 27, 37, 47, 57],
 [19, 29, 39, 49, 59]
])

print(A)
print("Shape:", A.shape)

[[10 20 30 40 50]
 [15 25 35 45 55]
 [12 22 32 42 52]
 [17 27 37 47 57]
 [19 29 39 49 59]]
Shape: (5, 5)


#### Hint: import numpy as np before creating the array

<h4 style="color:blue">Question #1B - Print Number of Dimensions</h4> Using the same array <b>A</b>, print the <b>ndim</b> (number of dimensions).<br><br>

In [3]:
print("Dimensions:", A.ndim)

Dimensions: 2


<h4 style="color:blue">Question #1C - Print Data Type</h4> Using array <b>A</b>, print the <b>dtype</b>.<br><br>

In [4]:
print(type(A))

<class 'numpy.ndarray'>


<h4 style="color:blue">Question #1D - Print Total Elements</h4> Using array <b>A</b>, print the <b>size</b> (total number of elements).<br><br>

In [5]:
print("Size:", A.size)

Size: 25


<h4 style="color:blue">Question #2 - Index 2nd and 4th Rows</h4> From array <b>A</b>, index rows <b>1</b> and <b>3</b> (2nd and 4th rows).<br><br>

In [6]:
A[[1,3], :]

array([[15, 25, 35, 45, 55],
       [17, 27, 37, 47, 57]])

<h4 style="color:blue">Question #3 - Index the First Three Rows</h4> From array <b>A</b>, extract rows <b>0, 1, 2</b>.<br><br>

In [7]:
A[[0,1,2], :]

array([[10, 20, 30, 40, 50],
       [15, 25, 35, 45, 55],
       [12, 22, 32, 42, 52]])

<h4 style="color:blue">Question #4 - Index the Last Two Rows</h4> From array <b>A</b>, extract rows <b>3</b> and <b>4</b>.<br><br>

In [8]:
A[-2:, :]

array([[17, 27, 37, 47, 57],
       [19, 29, 39, 49, 59]])

<h4 style="color:blue">Question #5 - Index the First Column Only</h4> From array <b>A</b>, extract column <b>0</b> only.<br><br>

In [9]:
A[:, 0]

array([10, 15, 12, 17, 19])

<h4 style="color:blue">Question #6 - Index the Last Column Only</h4> From array <b>A</b>, extract column <b>4</b> only.<br><br>

In [10]:
A[:, -1]

array([50, 55, 52, 57, 59])

<h4 style="color:blue">Question #7 - Index the Middle Row (Row 3)</h4> From array <b>A</b>, extract row <b>2</b> (middle row).<br><br>

In [11]:
A[2, :]

array([12, 22, 32, 42, 52])

<h4 style="color:blue">Question #8 - Index the Middle Column (Column 3)</h4> From array <b>A</b>, extract column <b>2</b> (middle column).<br><br>

In [12]:
A[2, :]

array([12, 22, 32, 42, 52])

<h4 style="color:blue">Question #9 - Top-Left 3×3 Block</h4> From array <b>A</b>, extract the block of rows <b>0 to 2</b> and columns <b>0 to 2</b>.<br><br>

In [13]:
A[:3, :3]

array([[10, 20, 30],
       [15, 25, 35],
       [12, 22, 32]])

<h4 style="color:blue">Question #10 - Index Every Alternate Row</h4> From array <b>A</b>, extract rows <b>0, 2, 4</b> using step slicing.<br><br>

### Array Operations Section (New Dataset)

Dataset <b>B</b>:<br>
[[5, 8, 12],<br>
 [3, 15, 20],<br>
 [7, 10, 25]]<br><br>
 
 <h4 style="color:blue">Question #11 - Add 10 to Every Element</h4> Using array <b>B</b>, add <b>10</b> to every element and print the updated array.<br><br>

In [14]:
B = [[5, 8, 12],[3, 15, 20],[7, 10, 25]]
arrB = np.array(B)

arrB_add = arrB + 10
print(arrB_add)

[[15 18 22]
 [13 25 30]
 [17 20 35]]


<h4 style="color:blue">Question #12 - Multiply All Elements by 2</h4> Using array <b>B</b>, multiply every element by <b>2</b> and print the result.<br><br>

In [15]:
BC = arrB_add * 2
print(BC)

[[30 36 44]
 [26 50 60]
 [34 40 70]]


<h4 style="color:blue">Question #13 - Column-Wise Sum</h4> Using array <b>B</b>, compute the <b>sum of each column</b>.<br><br>

In [23]:
B =arrB.sum(axis = 0)
print(B)

[15 33 57]


<h4 style="color:blue">Question #14 - Row-Wise Maximum</h4> Using array <b>B</b>, print the <b>maximum value from each row</b>.<br><br>

In [24]:
B =arrB.sum(axis = 1)
print(B)

[25 38 42]


<h4 style="color:blue">Question #15 - Comparison: Elements Greater Than 10</h4> Using array <b>B</b>, check which elements are <b>greater than 10</b> and print the Boolean output.<br><br>

In [25]:
mask = arrB > 10
print("Mask:", mask)
print("Filtered prices:", arrB[mask])

Mask: [[False False  True]
 [False  True  True]
 [False False  True]]
Filtered prices: [12 15 20 25]
